language: python

python:
  - 3.8

before_install:
  # Install the latest version of Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt

install:
  # Create a new Conda environment
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  # Activate it
  - source activate test
  # Install various dependencies
  - conda install --yes -c conda-forge "tensorflow-gpu>=2.2.0" numpy scipy

script:
  - cd $TRAVIS_BUILD_DIR/test/
  - "travis_wait python build_test.py"
